version: '3.8'

services:
  product_service:
    build: ./microservices/product_service
    ports:
      - "8001:8000"
    env_file:
      - ./microservices/product_service/.env
    depends_on:
      - db

  user_service:
    build: ./microservices/user_service
    ports:
      - "8002:8000"
    env_file:
      - ./microservices/user_service/.env
    depends_on:
      - db

  order_service:
    build: ./microservices/order_service
    ports:
      - "8003:8000"
    env_file:
      - ./microservices/order_service/.env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
